### ISSUE TITLE
Escaping variables

### ISSUE THREAD

**Issue by alexpate** [reshape/expressions#19]
Is there a way to escape variables?

Am building a project that uses Vue, which also uses the `{{ variable }}` syntax. Ideally, I don't want reshape to pick up on these.

Is something like this possible: `@{{ variable}}` which compiles down to `{{ variable }}`

**Comment by tkraak** [comment]
@alexpate ... see `delimiters` and `unescapeDelimiters` in [options](https://github.com/reshape/expressions#usage).

**Comment by jescalan** [comment]
Yep, that will do it!
