### ISSUE TITLE
Issue with conditional and nested expression

### ISSUE THREAD

**Issue by michaelcd** [reshape/expressions#8]
It seems expressions contained within an `else` will not work.

Using a fresh install of spike 0.12.1 and creating a new project:
`if(condition='true'): h4 {{ foo }}` correctly outputs `<h4>bar</h4>`

However the below incorrectly outputs `<h4>{{ foo }}</h4>`

``` jade
if(condition='false)
  h4 test
else
  h4 {{ foo }}  
```

**Comment by jescalan** [comment]
Confirmed, this is a bug. Will try to have a patch out today!
